# Generated by Django 4.0.3 on 2022-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
