# Generated by Django 4.0.3 on 2022-04-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0011_cart_brand_name_cart_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
