# Generated by Django 4.0.3 on 2022-04-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0012_remove_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
